encoding: utf-8
name: Raghav Bali
url: http://raghavbali.github.io/
author:
  name: Raghav Bali
description: Senior Data Scientist at Optum (United HealthGroup). Author. Shutterbug
permalink: /posts/:title/
include: ['_pages']
